version: 1.0.{build}
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: KztQKStikpPv2BcLUeyQczT+vis86eh0H/PPqnhJ+umDIvjJZzjmNzTj/E3ZFo7q